### PR TITLE
Fixed #95.

### LINKED ISSUE #95: 查看报名结果的界面最好能做一个到修改界面的导航吧

### PR DESCRIPTION
**Pull request by cindywang319**
在察看结果页面增加了修改人员信息的按钮

### CODE REVIEW

**Comment by huxuan** [comment]
Please revert the chage in `application/controllers/registration.php` as there will be a conflict.

**Comment by cindywang319** [comment]
ok, checked

**Comment by huxuan** [comment]
So did you forget to push new commits? I don't see any changes by your comment.

**Comment by cindywang319** [comment]
失误了失误了 现在好了

**Pull request merged**
