### PR TITLE
Add editor for admin.

### PR DESCRIPTION
**Pull request by JeldorPKU**
Now the admin can edit the documentations.

### CODE REVIEW

**Comment by huxuan** [comment]
I would suggest we can use some package manager for CKEditor [1]. npm is more popular from my personal preference.

[1] http://docs.ckeditor.com/#!/guide/dev_package_managers

**Comment by JeldorPKU** [comment]
So I should make CKEditor ignored?
I am not quite sure what I should do about this.
@huxuan

**Comment by huxuan** [comment]
Yep, hard coding copy of CKEditor is not necessary. In short, we can create a `package.json` file [1] and have CKEditor as dependency [2], Then whenever we want to deploy the whole website `npm install` command will download all the dependent packages for us. Feel free to play a little bit with npm, it just works like pip for Python.

[1] https://docs.npmjs.com/getting-started/using-a-package.json#creating-a-packagejson
[2] https://docs.npmjs.com/getting-started/using-a-package.json#the---save-and---save-dev-install-flags

**Comment by JeldorPKU** [comment]
OK I will try it out soon.

**Comment by huxuan** [comment]
You can also take a look at the section `Adding CKEditor as a Dependency Using the `package.json` File` here [1]. Seems the creation of `package.json` is not required. Just `npm install` with `--save` flag will create a minimal `pckage.json` for us. After that, we need to have `package.json` under version control while `node_modules` directory ignored.

[1] http://docs.ckeditor.com/#!/guide/dev_package_managers

**Comment by JeldorPKU** [comment]
Done~
But is it proper to put `ckeditor_config.js` in the root directory?
@huxuan

**Comment by huxuan** [comment]
I suggest we locate it along with other Javascript files, which is `/assets/js/`.

**Pull request merged**
